language: go

go:
  - "1.16"
  - tip

group: bluezone

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

cache:
  bundler: true

sudo: true

before_install:
  - sudo apt-get install bc

before_script:
  - make deps
  - go get github.com/pierrre/gotestcover

script:
  - make dofmt
  - travis_wait 300 make test   
  - make ut-coverage && touch "Passing" || touch "Failed"


after_success:
- "./scripts/calculateCoverage.sh"
- "./scripts/publishCoverage.sh"

after_failure:
- "./scripts/handleFailure.sh"
