name: Quality
on: [push, pull_request]
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    name: Test with Coverage
    runs-on: ubuntu-latest
    container:
      image: golang:1.16
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: {{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Unit tests
      run: |
        go test $(go list ./... | grep -v /vendor/ | grep -v /cmd | grep -v /tests) -race -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      env:
        GOPATH: ${{ github.workspace }}
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      run: $GOPATH/bin/goveralls -coverprofile=covprofile -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: ${{ github.workspace }}
