name: Quality
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    container:
      image: golang:1.16
      env:
        GOPATH: /__w/ibm-vpc-block-csi-driver/ibm-vpc-block-csi-driver/go/
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver
    - name: Install dependencies
      working-directory: /__w/ibm-vpc-block-csi-driver/ibm-vpc-block-csi-driver/go/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver
      run: |
        go mod download
    - name: Run Unit tests
      run: |
        working-directory: /__w/ibm-vpc-block-csi-driver/ibm-vpc-block-csi-driver/go/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver
        go test $(go list ./... | grep -v /vendor/ | grep -v /cmd | grep -v /tests) -race -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      env:
        GOPATH: /__w/ibm-vpc-block-csi-driver/ibm-vpc-block-csi-driver/go/
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: /__w/ibm-vpc-block-csi-driver/ibm-vpc-block-csi-driver/go
      run: $(GOPATH)/bin/goveralls -coverprofile=covprofile -service=github
