name: Quality
on: [push, pull_request]
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Unit tests
      run: |
        go test $(go list ./... | grep -v /vendor/ | grep -v /cmd | grep -v /tests) -v -covermode=count -coverprofile=coverage.out
    - name: Install goveralls
      env:
        GOPATH: ${{ github.workspace }}
      run: |
         go install github.com/mattn/goveralls@latest 
         go get golang.org/x/tools/cmd/cover
      
    - name: Send coverage
      run: $GOPATH/bin/goveralls -coverprofile=coverage.out -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: ${{ github.workspace }}

